window.VMS_EZ_FIXTURES = {
  zones: [
    { key: "reception", label: "Reception / Lobby" },
    { key: "admin", label: "Admin block" },
    { key: "classroom", label: "Classroom wing" },
    { key: "sports", label: "Sports / playground" },
    { key: "lab", label: "Labs / IT" },
    { key: "restricted", label: "Restricted (principal / accounts / stores / server)" },
    { key: "parking", label: "Bus bay / parking" },
  ],
  rules: [
    { visitorType: "Vendor", escortRequired: true, allowedZones: ["reception", "admin"] },
    { visitorType: "Parent", escortRequired: false, allowedZones: ["reception"] },
    { visitorType: "Guest", escortRequired: false, allowedZones: ["reception"] },
    { visitorType: "Official", escortRequired: false, allowedZones: ["reception", "admin"] },
    { visitorType: "Alumni", escortRequired: false, allowedZones: ["reception"] },
  ],
  /* Live mock escort directory is E01 Vikram More only. Never seed E02/E03. */
  escorts: [
    { id: "E01", name: "Vikram More", roleTitle: "Gate / lobby · on duty" },
  ],
  ravi: {
    id: "V-EZ-VENDOR",
    visitorName: "Ravi Deshmukh",
    mobile: "9876544021",
    visitorType: "Vendor",
    purpose: "A/C maintenance — Block B",
    hostId: "H03",
    hostName: "Anita Joshi",
    hostRole: "Primary Coordinator",
    gateId: "G-MAIN",
    gateName: "Main Gate",
    status: "approved",
    afterHours: true,
    policyTrigger: "outside_hours",
    afterHoursEvaluatedAt: "2026-09-16T19:42:00+05:30",
    createdAt: "2026-09-16T19:42:00+05:30",
    passId: "P-7K88",
    qrToken: "demo-qr-token-P-7K88-escort",
    escortRequired: true,
    allowedZones: ["reception", "admin"],
    escortStaffId: null,
    escortName: null,
    escortSuggestedByHost: null,
    escortWaived: false,
    escortWaiveReason: null,
    escortClearedAt: null,
  },
  suresh: {
    id: "V-EZ-WAIVED",
    visitorName: "Suresh Patil",
    passId: "P-6H03",
    visitorType: "Vendor",
    escortRequired: true,
    allowedZones: ["reception"],
    escortStaffId: null,
    escortName: null,
    escortWaived: true,
    escortWaiveReason: "No escort staff — SH waive",
    status: "completed",
  },
};
