window.VMS_AH_FIXTURES = {
  timezone: "Asia/Kolkata",
  hours: [
    { weekday: "mon", openTime: "08:00", closeTime: "18:00", closed: false },
    { weekday: "tue", openTime: "08:00", closeTime: "18:00", closed: false },
    { weekday: "wed", openTime: "08:00", closeTime: "18:00", closed: false },
    { weekday: "thu", openTime: "08:00", closeTime: "18:00", closed: false },
    { weekday: "fri", openTime: "08:00", closeTime: "18:00", closed: false },
    { weekday: "sat", openTime: "08:00", closeTime: "13:00", closed: false },
    { weekday: "sun", openTime: null, closeTime: null, closed: true },
  ],
  holidays: [
    { id: "HOL-DIWALI", date: "2026-10-20", label: "Diwali" },
  ],
  ravi: {
    id: "V-AH-VENDOR",
    visitorName: "Ravi Deshmukh",
    mobile: "9876544021",
    visitorType: "Vendor",
    purpose: "A/C maintenance — Block B",
    hostId: "H03",
    hostName: "Anita Joshi",
    hostRole: "Primary Coordinator",
    gateId: "G-MAIN",
    gateName: "Main Gate",
    status: "pending",
    afterHours: true,
    policyTrigger: "outside_hours",
    afterHoursEvaluatedAt: "2026-09-16T19:42:00+05:30",
    createdAt: "2026-09-16T19:42:00+05:30",
    passId: null,
  },
  deepak: {
    id: "V-AH-HOLIDAY",
    visitorName: "Deepak Nair",
    mobile: "9822098802",
    visitorType: "Parent",
    purpose: "Holiday walk-in — collect notebooks",
    hostId: "H01",
    hostName: "Meera Kulkarni",
    hostRole: "Principal",
    gateId: "G-MAIN",
    gateName: "Main Gate",
    status: "approved",
    afterHours: true,
    policyTrigger: "holiday",
    afterHoursEvaluatedAt: "2026-10-20T10:30:00+05:30",
    createdAt: "2026-10-20T10:30:00+05:30",
    passId: "P-7K88",
    qrToken: "demo-qr-token-P-7K88",
  },
};
